<?php

/*
	$ [PHPMark2]   /call/t1.php , 150216   (C) 2005-2015 MF
*/


require_once './phpmark.php';



// ===== 0 ===================================================================

	$d	= PHPMark::Resource ('32768');

	$d	= $d.$d.$d.$d.$d.$d.$d.$d.
		  $d.$d.$d.$d.$d.$d.$d.$d.
		  $d.$d.$d.$d.$d.$d.$d.$d.
		  $d.$d.$d.$d.$d.$d.$d.$d;

// ===== 0 ===================================================================



PHPMark::BaseBegin ( );

// ===== 1 ===================================================================

// ===== 1 ===================================================================

PHPMark::BaseEnd ( );



PHPMark::TestBegin ( );

// ===== 2 ===================================================================

	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);
	token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d); token_get_all ($d);

// ===== 2 ===================================================================

PHPMark::TestEnd ( );



PHPMark::Mark ( );
PHPMark::Data (2000, 1048576, 'B/s');

exit;

