<?php

/*
	$ [PHPMark2]   /call/t12.php , 150216   (C) 2005-2015 MF
*/


require_once './phpmark.php';



// ===== 0 ===================================================================

	$i	= 0;
	$f	= PHPMark::ResourceFile ('32768');

// ===== 0 ===================================================================



PHPMark::BaseBegin ( );

// ===== 1 ===================================================================

	for($i = 0; $i < 100; $i ++)
		;

// ===== 1 ===================================================================

PHPMark::BaseEnd ( );



PHPMark::TestBegin ( );

// ===== 2 ===================================================================

	for($i = 0; $i < 100; $i ++)
	{
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
		file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f); file_get_contents($f);
	}

// ===== 2 ===================================================================

PHPMark::TestEnd ( );



PHPMark::Mark ( );
PHPMark::Data (100 * 1000, 32768, 'B/s');

exit;

