<?php

/*
	$ [PHPMark2]   /call/t13.php , 150216   (C) 2005-2015 MF
*/


require_once './phpmark.php';



// ===== 0 ===================================================================

	$i	= 0;

// ===== 0 ===================================================================



PHPMark::BaseBegin ( );

// ===== 1 ===================================================================

	for($i = 0; $i < 2500; $i ++)
		;

// ===== 1 ===================================================================

PHPMark::BaseEnd ( );



PHPMark::TestBegin ( );

// ===== 2 ===================================================================

	for($i = 0; $i < 2500; $i ++)
	{
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
		chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1)); chr(ord(1));
	}

// ===== 2 ===================================================================

PHPMark::TestEnd ( );



PHPMark::Mark ( );
PHPMark::Data (2500, 5000, 'Conv/s');

exit;

