<?php

/*
	$ [PHPMark2]   /call/t8.php , 150216   (C) 2005-2015 MF
*/


require_once './phpmark.php';



// ===== 0 ===================================================================

	$i	= 0;
	$a	= array ( );

	for($i = 0; $i < 50000; $i ++)
		$a [ ]	= $i;

// ===== 0 ===================================================================



PHPMark::BaseBegin ( );

// ===== 1 ===================================================================

// ===== 1 ===================================================================

PHPMark::BaseEnd ( );



PHPMark::TestBegin ( );

// ===== 2 ===================================================================

	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);
	json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a); json_encode($a);

// ===== 2 ===================================================================

PHPMark::TestEnd ( );



PHPMark::Mark ( );
PHPMark::Data (2000, count ($a), 'Ent/s');

exit;

